# This is a basic workflow to help you get started with Actions

name: qndxx

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 8 */3 * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Cherkout
      uses: actions/checkout@v2
  
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
        
    - name: main
      env:
        PYTHONIOENCODING: utf-8
        PYTHONLEGACYWINDOWSSTDIO: utf-8
      run: python main.py
